import type { ReliefData } from "@/lib/relief/types";

// Google Sheets 未接続時に表示するサンプルデータ（熊本での現地支援を想定した架空の内容）。
// シート構成・ID 連携（docs/DESIGN.md）のリファレンス実装を兼ねる。
// 日付は「今日（JST）」を基準にした相対値で生成し、いつ開いてもデモが成立するようにする。

/** 今日から offset 日ずらした日付（JST・YYYY-MM-DD）。 */
function day(offset: number): string {
  const d = new Date(Date.now() + offset * 24 * 60 * 60 * 1000);
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Tokyo",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(d);
}

export const RELIEF_SEED: ReliefData = {
  disasterName: "熊本地震 現地支援（サンプル）",
  hq: "熊本市中央区・現地支援本部",
  basisDate: day(0),
  members: [
    {
      id: "M-01",
      name: "佐藤 一郎",
      kana: "さとう いちろう",
      org: "慶應義塾大学",
      role: "統括",
      groupId: "G-1",
      phone: "090-0000-0001",
      email: "sato@example.com",
    },
    {
      id: "M-02",
      name: "鈴木 花子",
      kana: "すずき はなこ",
      org: "慶應義塾大学",
      role: "物資調整",
      groupId: "G-1",
      phone: "090-0000-0002",
      email: "suzuki@example.com",
    },
    {
      id: "M-03",
      name: "高橋 健",
      kana: "たかはし けん",
      org: "静岡県",
      role: "避難所支援",
      groupId: "G-2",
      phone: "090-0000-0003",
      email: "takahashi@example.com",
    },
    {
      id: "M-04",
      name: "田中 美咲",
      kana: "たなか みさき",
      org: "静岡県",
      role: "記録・広報",
      groupId: "G-2",
      phone: "090-0000-0004",
      email: "tanaka@example.com",
    },
    {
      id: "M-05",
      name: "伊藤 大輔",
      kana: "いとう だいすけ",
      org: "NPO法人サンプル",
      role: "輸送",
      groupId: "G-2",
      phone: "090-0000-0005",
      email: "ito@example.com",
    },
  ],
  groups: [
    { id: "G-1", name: "本部班", mission: "全体統括・物資調整・関係機関連絡", leaderId: "M-01" },
    { id: "G-2", name: "現地班", mission: "避難所支援・ヒアリング・輸送", leaderId: "M-03" },
  ],
  schedule: [
    {
      id: "SC-001",
      date: day(0),
      start: "09:00",
      end: "09:30",
      scope: "全体",
      title: "朝会（全体ミーティング）",
      place: "現地支援本部",
    },
    {
      id: "SC-002",
      date: day(0),
      start: "10:00",
      end: "12:00",
      scope: "グループ",
      targetId: "G-2",
      title: "益城町総合体育館 訪問・ヒアリング",
      place: "益城町総合体育館",
    },
    {
      id: "SC-003",
      date: day(0),
      start: "14:00",
      end: "15:00",
      scope: "グループ",
      targetId: "G-1",
      title: "県庁 物資調整会議",
      place: "熊本県庁",
    },
    {
      id: "SC-004",
      date: day(0),
      start: "16:00",
      end: "17:00",
      scope: "個人",
      targetId: "M-04",
      title: "取材対応（地元紙）",
      place: "現地支援本部",
    },
    {
      id: "SC-005",
      date: day(1),
      start: "09:00",
      end: "09:30",
      scope: "全体",
      title: "朝会（全体ミーティング）",
      place: "現地支援本部",
    },
    {
      id: "SC-006",
      date: day(1),
      start: "10:30",
      end: "12:00",
      scope: "グループ",
      targetId: "G-2",
      title: "南阿蘇村 支援拠点 物資受け入れ",
      place: "南阿蘇村体育館",
    },
    {
      id: "SC-007",
      date: day(2),
      start: "18:00",
      end: "19:00",
      scope: "全体",
      title: "振り返り・申し送り会",
      place: "現地支援本部",
    },
  ],
  bookings: [
    {
      id: "B-001",
      memberId: "M-01",
      type: "飛行機",
      startDate: day(-1),
      name: "ANA 641（羽田→熊本）",
      detail: "15:30発 / 17:25着",
      confNo: "ANA-123456",
      status: "予約済",
    },
    {
      id: "B-002",
      memberId: "M-01",
      type: "ホテル",
      startDate: day(-1),
      endDate: day(3),
      name: "ホテル熊本サンプル",
      detail: "シングル・朝食付",
      confNo: "HTL-98765",
      status: "予約済",
    },
    {
      id: "B-003",
      memberId: "M-03",
      type: "新幹線",
      startDate: day(-1),
      name: "のぞみ25号→さくら405号（静岡→熊本）",
      detail: "09:12発 / 14:02着",
      status: "予約済",
    },
    {
      id: "B-004",
      memberId: "M-05",
      type: "レンタカー",
      startDate: day(0),
      endDate: day(3),
      name: "サンプルレンタカー熊本空港店",
      detail: "バン（物資輸送用）",
      confNo: "RC-2468",
      status: "仮予約",
    },
  ],
  supplies: [
    {
      id: "SP-001",
      lotNo: "LOT-2026-0815-01",
      item: "飲料水 500ml",
      category: "水・飲料",
      qty: "1200",
      unit: "本",
      from: "静岡県庁",
      toShelterId: "SH-01",
      status: "到着",
      shipDate: day(-3),
      arriveDate: day(-1),
      requestId: "R-001",
    },
    {
      id: "SP-002",
      lotNo: "LOT-2026-0816-01",
      item: "簡易トイレ",
      category: "衛生用品",
      qty: "300",
      unit: "個",
      from: "支援企業A",
      toShelterId: "SH-01",
      status: "輸送中",
      shipDate: day(-1),
      requestId: "R-002",
    },
    {
      id: "SP-003",
      lotNo: "LOT-2026-0816-02",
      item: "毛布",
      category: "生活用品",
      qty: "500",
      unit: "枚",
      from: "日本赤十字社サンプル支部",
      toShelterId: "SH-02",
      status: "手配中",
    },
    {
      id: "SP-004",
      lotNo: "LOT-2026-0817-01",
      item: "アルファ米",
      category: "食料",
      qty: "2000",
      unit: "食",
      from: "静岡県庁",
      toShelterId: "SH-03",
      status: "輸送中",
      shipDate: day(0),
      requestId: "R-003",
    },
  ],
  requests: [
    {
      id: "R-001",
      date: day(-4),
      shelterId: "SH-01",
      content: "飲料水が不足。500ml ペットボトル希望",
      qty: "1000本以上",
      urgency: "高",
      status: "対応済",
    },
    {
      id: "R-002",
      date: day(-3),
      shelterId: "SH-01",
      content: "仮設トイレ・簡易トイレの追加",
      qty: "200個",
      urgency: "高",
      status: "手配中",
    },
    {
      id: "R-003",
      date: day(-2),
      shelterId: "SH-03",
      content: "非常食（アレルギー対応含む）",
      qty: "2000食",
      urgency: "中",
      status: "手配中",
    },
    {
      id: "R-004",
      date: day(-1),
      shelterId: "SH-02",
      content: "乳幼児用ミルク・おむつ",
      urgency: "高",
      status: "受付",
    },
  ],
  shelters: [
    {
      id: "SH-01",
      name: "益城町総合体育館",
      type: "避難所",
      address: "熊本県上益城郡益城町木山236",
      contactName: "避難所運営 担当者",
      phone: "096-000-0001",
      capacity: "800",
      current: "620",
      needs: "水・簡易トイレ・プライバシー確保",
      status: "開設",
    },
    {
      id: "SH-02",
      name: "熊本市総合体育館",
      type: "避難所",
      address: "熊本市中央区出水2-7-1",
      contactName: "市職員 担当者",
      phone: "096-000-0002",
      capacity: "600",
      current: "410",
      needs: "毛布・乳幼児用品",
      status: "開設",
    },
    {
      id: "SH-03",
      name: "南阿蘇村体育館",
      type: "支援拠点",
      address: "熊本県阿蘇郡南阿蘇村河陰145-3",
      contactName: "村職員 担当者",
      phone: "0967-00-0003",
      capacity: "400",
      current: "180",
      needs: "非常食・燃料",
      status: "開設",
    },
  ],
  contacts: [
    {
      id: "C-01",
      org: "熊本県 危機管理防災課",
      name: "県担当者",
      category: "自治体",
      phone: "096-000-1001",
      email: "bousai@example.pref.kumamoto.jp",
    },
    {
      id: "C-02",
      org: "益城町役場 総務課",
      name: "町担当者",
      category: "自治体",
      phone: "096-000-1002",
      shelterId: "SH-01",
    },
    {
      id: "C-03",
      org: "熊本市社会福祉協議会",
      name: "ボランティアセンター担当",
      category: "社協",
      phone: "096-000-1003",
      shelterId: "SH-02",
    },
    {
      id: "C-04",
      org: "熊本赤十字病院（サンプル）",
      name: "救護班窓口",
      category: "医療",
      phone: "096-000-1004",
    },
    {
      id: "C-05",
      org: "NPO法人くまもと支援ネット（サンプル）",
      name: "事務局",
      category: "NPO",
      phone: "096-000-1005",
      email: "npo@example.org",
    },
  ],
  logs: [
    {
      id: "L-001",
      datetime: `${day(-1)} 18:30`,
      kind: "時系列",
      reporter: "佐藤 一郎",
      title: "先遣隊 熊本着。現地支援本部を設置",
      content: "県庁・益城町役場へ挨拶。明日から避難所巡回を開始する。",
      visibility: "共有",
      authorId: "M-01",
    },
    {
      id: "L-002",
      datetime: `${day(0)} 11:30`,
      kind: "ヒアリング",
      reporter: "高橋 健",
      shelterId: "SH-01",
      title: "益城町総合体育館 運営者ヒアリング",
      content:
        "避難者約620名。水は充足したが簡易トイレが依然不足。高齢者の割合が高く、段ボールベッドの追加希望あり。夜間の照明が暗く不安の声。",
      tags: "トイレ,段ボールベッド,照明",
      visibility: "共有",
      authorId: "M-03",
    },
    {
      id: "L-003",
      datetime: `${day(0)} 15:00`,
      kind: "指示・決定",
      reporter: "佐藤 一郎",
      title: "簡易トイレ200個の追加手配を決定",
      content: "県物資調整会議にて。支援企業Aから直送、明日着予定。",
      shelterId: "SH-01",
      visibility: "共有",
      authorId: "M-01",
    },
    {
      id: "L-004",
      datetime: `${day(0)} 17:45`,
      kind: "申し送り",
      reporter: "田中 美咲",
      title: "取材対応の記録",
      content: "地元紙より支援活動の取材。掲載は明後日の朝刊予定。写真は本部前で撮影。",
      visibility: "共有",
      authorId: "M-04",
    },
    {
      id: "L-005",
      datetime: `${day(0)} 19:10`,
      kind: "ヒアリング",
      reporter: "田中 美咲",
      shelterId: "SH-02",
      title: "熊本市総合体育館の様子メモ",
      content: "乳幼児連れの世帯が増えている印象。ミルク・おむつの在庫を明日確認してから共有する。",
      visibility: "下書き",
      authorId: "M-04",
    },
  ],
  images: [],
  source: "seed",
};
